# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
development:
  SENDGRID_USERNAME: 'app19630349@heroku.com'
  SENDGRID_PASSWORD: 'pbuiirig'
  STRIPE_API_KEY: 'sk_test_4TMTbBoxjjkSAIgCaVLQqdDL'
  STRIPE_PUBLIC_KEY: 'pk_test_9ZFcJunFaJpY7C6FXkw9iZAT'
production:
  SENDGRID_USERNAME: 'app19630349@heroku.com'
  SENDGRID_PASSWORD: 'pbuiirig'